# Generated by Django 4.2.7 on 2024-01-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('college', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=100)),
                ('semester', models.PositiveIntegerField()),
                ('skill', models.TextField()),
                ('start_date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('github', models.URLField(blank=True, null=True)),
                ('cv', models.FileField(upload_to='cv_pdfs/')),
            ],
        ),
    ]
