# Generated by Django 4.2.7 on 2024-01-11 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Student_details',
        ),
    ]
