# Generated by Django 4.2.7 on 2024-01-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0002_rename_student_student_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
