# Generated by Django 4.2.7 on 2024-01-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0003_alter_student_details_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
