# Generated by Django 4.2.7 on 2024-01-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0004_student_details_linkedin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_details',
            new_name='Student_info',
        ),
    ]
