# Generated by Django 4.2.7 on 2024-01-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_title', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('category', models.CharField(max_length=50)),
                ('timing', models.CharField(max_length=50)),
                ('form_due_date', models.DateField()),
            ],
        ),
    ]
